networks:
  wordpress-cloud:
    driver: bridge

services:
  wordpress-php:
    build:
      context: ./images/php-84
      dockerfile: Dockerfile
    container_name: wordpress-cloud-php
    restart: unless-stopped
    volumes:
      - ./www:/var/www/html
      - ./.env:/var/www/.env
    networks:
      - wordpress-cloud
    depends_on:
      - wordpress-db


  wordpress-nginx:
    image: nginx:latest
    container_name: wordpress-cloud-nginx
    restart: unless-stopped
    ports:
      - "${WEB_EXTERNAL_PORT}:80"
    volumes:
      - ./www:/var/www/html
      - ./images/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - wordpress-cloud
    depends_on:
      - wordpress-php

  wordpress-db:
    image: mariadb:latest
    container_name: wordpress-cloud-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USER}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    ports:
      - "${DB_EXTERNAL_PORT}:3306"
    networks:
      - wordpress-cloud
      
  wordpress-phpmyadmin:
    container_name: wordpress-cloud-phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
    - ${PHPMYADMIN_EXTERNAL_PORT}:80
    environment:
      PMA_ARBITRARY: "1"
      UPLOAD_LIMIT: ${PHP_MY_ADMIN_UPLOAD_LIMIT}
    networks:
    - wordpress-cloud

volumes:
  db_data:
